
/* lr1 lexical symbols (generated by LRSTAR). */

	<eof>                =>     1

	'c'                  =>     2
	't'                  =>     3
	'n'                  =>     5
	'r'                  =>     6
	'a'                  =>     7

	';'                  =>     4

%%

