
#pragma once

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                 //
//    LGLexer.h

/*    Generated by: DFASTAR 5.0.003
      Grammar:      LG.lgr
      Skeleton:     LGLexer.h.skl
      Output:       LGLexer.h
*/               
		#define  ushort unsigned short
		#define  uchar  unsigned char

		class LGLexer 
		{
			public:
         static Token  token;
			static int    line_numb;
			static int    col_numb;			
			static int    line_pos;
			static char*  line_start;
			static int    max_char_set;
			static int	  tab;

			static int    get_token ();
			static int    get_lookahead ();
			static void   init ();
			static void   term ();
			static void   prt_line ();

			static char* token_name[1];
		};

