
/* typedef lexical symbols (generated by LRSTAR). */

	<identifier>         =>     1
	<eof>                =>     2

	'typedef'            =>     5
	'char'               =>     8
	'int'                =>     9
	'short'              =>    10
	'unsigned'           =>    11

	','                  =>     3
	';'                  =>     4
	'*'                  =>     7

%%

